# Header
menu:
  主页: /
  文章: /archives
  项目: /project
  关于: /about
  # 简历: /resume

# SubNav
subnav:
  github: "https://github.com/MarkMjw"
  weibo: "http://weibo.com/markmjw"
  # rss: "#"
  # facebook: "#"
  # google: "#"
  # twitter: "#"
  linkedin: "https://www.linkedin.com/profile/view?id=328037702"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.png

#你的头像
avatar: "http://gravatar.com/avatar/556826198e4e0e1e1566f502f5fcc896?s=200"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: true
#是否开启云标签
tagcloud: false

#是否开启友情链接
#不开启——
friends: false
#开启——
friends:
  奥巴马的博客: http://localhost:4000/
  卡卡的美丽传说: http://localhost:4000/
  本泽马的博客: http://localhost:4000/
  吉格斯的博客: http://localhost:4000/
  习大大大不同: http://localhost:4000/
  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…